apiVersion: v1
kind: Service
metadata:
  name: securegate-service
  namespace: default
spec:
  type: NodePort # 🔌 Opens an accessible target port across your cluster nodes
  selector:
    app: securegate # Dynamically routes traffic to any pods labeled 'securegate'
  ports:
    - port: 80         # The port the service listens on inside the cluster
      targetPort: 5000 # The internal container port where Flask is active
      nodePort: 30096  # 🔒 Permanently locks in the port number we tested today!
